const cfg=window.NITEK_CONFIG;const sb=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);const $=id=>document.getElementById(id);const esc=x=>String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));let USER=null;
async function init(){let {data}=await sb.auth.getUser();USER=data.user;if(!USER){location.href="login.html";return}let d=new Date();$("date").value=d.toISOString().slice(0,10);$("time").value=d.toTimeString().slice(0,5);await home();show("home")}
function show(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$(id)?.classList.add("active");document.querySelectorAll(".bottom button").forEach(x=>x.classList.remove("active"));document.querySelector(`[data-page="${id}"]`)?.classList.add("active");if(id==="home")home();if(id==="customers")customers();if(id==="services")services();if(id==="faults")faults();if(id==="reports")reports();if(id==="service")initService()}
async function home(){let [{data:c},{data:s}]=await Promise.all([sb.from("customers").select("*",{count:"exact"}),sb.from("services").select("*")]);c=c||[];s=s||[];let total=s.reduce((a,x)=>a+Number(x.total||0),0);$("homeStats").innerHTML=`<div class=grid><div class=list><b>${c.length}</b><br><span class=muted>Müşteri</span></div><div class=list><b>${s.length}</b><br><span class=muted>Servis</span></div><div class=list><b>${s.filter(x=>x.type==="Bakım").length}</b><br><span class=muted>Bakım</span></div><div class=list><b>${total.toFixed(2)} ₺</b><br><span class=muted>Ciro</span></div></div>`;$("recent").innerHTML=s.slice(0,5).map(card).join("")||"<p class=muted>Henüz servis yok.</p>"}
function card(s){return `<div class=list><b>${esc(s.type)} • ${esc(s.device)}</b><h3>${esc(s.customer_name)}</h3><p class=muted>${esc(s.brand)} ${esc(s.model)}<br>${esc(s.service_date)} ${esc(s.service_time)}</p><b>${Number(s.total||0).toFixed(2)} ₺</b><div class=actions><button class=light onclick="detail('${s.id}')">Detayı Gör</button><button class=light onclick="makePDF('${s.id}')">PDF</button></div></div>`}
async function customers(){let q=($("customerSearch").value||"").trim();let query=sb.from("customers").select("*").order("created_at",{ascending:false});if(q)query=query.or(`name.ilike.%${q}%,phone.ilike.%${q}%`);let {data}=await query;$("customerList").innerHTML=(data||[]).map(c=>`<div class=list><h3>${esc(c.name)}</h3><p>📞 ${esc(c.phone)}<br>📍 ${esc(c.address)}</p><div class=actions><button class=blue onclick="newFor('${c.id}')">Yeni Servis</button><button class=light onclick="history('${c.id}')">Servis Geçmişi</button></div></div>`).join("")||"<p class=muted>Müşteri yok.</p>"}
async function addCustomer(){let n=prompt("Ad soyad");if(!n)return;let p=prompt("Telefon")||"",a=prompt("Adres")||"",note=prompt("Not")||"";let {error}=await sb.from("customers").insert({user_id:USER.id,name:n,phone:p,address:a,note});if(error)alert(error.message);else customers()}
async function newFor(id){let {data:c}=await sb.from("customers").select("*").eq("id",id).single();show("service");setTimeout(()=>{$("customer").value=c.name;$("phone").value=c.phone;$("address").value=c.address},50)}
async function history(id){let {data:c}=await sb.from("customers").select("*").eq("id",id).single();let {data:s}=await sb.from("services").select("*").eq("customer_id",id).order("created_at",{ascending:false});$("historyTitle").innerHTML=`<h2>${esc(c.name)}</h2><p>${esc(c.phone)}<br>${esc(c.address)}</p>`;$("historyList").innerHTML=(s||[]).map(card).join("")||"<p class=muted>Servis geçmişi yok.</p>";show("history")}
function catalogs(d){return NITEK_DATA.brands[d]||{}}function brandList(){let c=catalogs($("device").value);$("brand").innerHTML='<option value="">Marka seç</option>'+Object.keys(c).map(x=>`<option>${esc(x)}</option>`).join("");modelList()}function modelList(){let c=catalogs($("device").value),b=$("brand").value;$("model").innerHTML='<option value="">Model seç</option>'+((c[b]||[]).map(x=>`<option>${esc(x)}</option>`).join(""))}
function initService(){brandList();serviceType()}function serviceType(){let t=$("type").value;$("maintBox").classList.toggle("hidden",t!=="Bakım");$("faultBox").classList.toggle("hidden",t!=="Arıza");if(t==="Bakım"){let a=NITEK_DATA.maintenance[$("device").value]||NITEK_DATA.maintenance.Diğer;$("checks").innerHTML=a.map((x,i)=>`<label class=check><input type=checkbox data-check="${i}">${esc(x)}</label>`).join("")}}
function allChecks(v){document.querySelectorAll("[data-check]").forEach(x=>x.checked=v)}
async function saveService(){let n=$("customer").value.trim();if(!n)return alert("Müşteri adı gerekli.");let {data:c}=await sb.from("customers").select("*").eq("name",n).maybeSingle();if(!c){let r=await sb.from("customers").insert({user_id:USER.id,name:n,phone:$("phone").value,address:$("address").value}).select().single();if(r.error)return alert(r.error.message);c=r.data}
let device=$("device").value,a=NITEK_DATA.maintenance[device]||NITEK_DATA.maintenance.Diğer,done=$("type").value==="Bakım"?a.filter((x,i)=>document.querySelector(`[data-check="${i}"]`)?.checked):[],labor=Number($("labor").value)||0,parts=Number($("parts").value)||0;
let row={user_id:USER.id,customer_id:c.id,customer_name:n,phone:$("phone").value,address:$("address").value,type:$("type").value,device,brand:$("brand").value,model:$("model").value,complaint:$("complaint").value,done_checks:done,work:$("work").value,parts_text:$("partsText").value,labor,parts,total:labor+parts,payment:$("payment").value,note:$("note").value,service_date:$("date").value,service_time:$("time").value};
let {error}=await sb.from("services").insert(row);if(error)return alert(error.message);alert("Servis buluta kaydedildi.");show("services")}
async function services(){let q=($("serviceSearch").value||"").trim();let query=sb.from("services").select("*").order("created_at",{ascending:false});if(q)query=query.or(`customer_name.ilike.%${q}%,brand.ilike.%${q}%,model.ilike.%${q}%,device.ilike.%${q}%`);let {data}=await query;$("serviceList").innerHTML=(data||[]).map(card).join("")||"<p class=muted>Servis yok.</p>"}
async function detail(id){let {data:s}=await sb.from("services").select("*").eq("id",id).single();$("detail").innerHTML=`<div class=card><button class=light onclick="show('services')">← Geri</button><h2>${esc(s.type)} • ${esc(s.device)}</h2><p><b>Müşteri:</b> ${esc(s.customer_name)}<br><b>Marka/Model:</b> ${esc(s.brand)} ${esc(s.model)}<br><b>Tarih:</b> ${esc(s.service_date)} ${esc(s.service_time)}</p><h3>☑️ Yapılan Kontroller</h3>${(s.done_checks||[]).length?`<ul>${s.done_checks.map(x=>`<li>✓ ${esc(x)}</li>`).join("")}</ul>`:"<p class=muted>İşaretlenen kontrol yok.</p>"}<h3>🧰 Yapılan İş</h3><p>${esc(s.work)}</p><h3>🔩 Parça / Malzeme</h3><p>${esc(s.parts_text)}</p><p>İşçilik: ${Number(s.labor).toFixed(2)} ₺<br>Parça: ${Number(s.parts).toFixed(2)} ₺<br><b>${Number(s.total).toFixed(2)} ₺</b></p><button class="primary full" onclick="makePDF('${s.id}')">📄 PDF Oluştur</button></div>`;show("detail")}
async function makePDF(id){let {data:s}=await sb.from("services").select("*").eq("id",id).single();let w=window.open("","_blank");if(!w)return alert("Açılır pencereye izin ver.");w.document.write(`<html><head><meta charset=utf-8><title>NİTEK Servis</title><style>body{font-family:Arial;padding:30px}header{display:flex;gap:15px;align-items:center;border-bottom:2px solid #07152f;padding-bottom:15px}header img{width:90px;height:90px;object-fit:contain}li{margin:7px}.btn{position:fixed;right:20px;top:20px}@media print{.btn{display:none}}</style></head><body><button class=btn onclick=print()>PDF / Yazdır</button><header><img src="logo.jpg"><div><h1>NİTEK TEKNİK SERVİS</h1><p>Kombi • Klima • Bakım • Onarım • Montaj</p></div></header><p><b>Müşteri:</b> ${esc(s.customer_name)}<br><b>Telefon:</b> ${esc(s.phone)}<br><b>Adres:</b> ${esc(s.address)}</p><p><b>Servis:</b> ${esc(s.type)}<br><b>Cihaz:</b> ${esc(s.device)}<br><b>Marka/Model:</b> ${esc(s.brand)} ${esc(s.model)}<br><b>Tarih:</b> ${esc(s.service_date)} ${esc(s.service_time)}</p><h3>Yapılan Kontroller</h3><ul>${(s.done_checks||[]).map(x=>`<li>✓ ${esc(x)}</li>`).join("")}</ul><h3>Yapılan İş</h3><p>${esc(s.work)}</p><h3>Parça / Malzeme</h3><p>${esc(s.parts_text)}</p><p>İşçilik: ${Number(s.labor).toFixed(2)} ₺<br>Parça: ${Number(s.parts).toFixed(2)} ₺<br><b>TOPLAM: ${Number(s.total).toFixed(2)} ₺</b></p><p>Müşteri İmzası: ____________ &nbsp;&nbsp; Teknisyen: ____________</p></body></html>`);w.document.close()}
function faults(){let q=($("faultSearch").value||"").toLocaleLowerCase("tr");$("faultList").innerHTML=NITEK_DATA.faults.filter(x=>x.join(" ").toLocaleLowerCase("tr").includes(q)).map(x=>`<div class=list><b>${esc(x[0])}</b> — ${esc(x[1])}<p class=muted>${esc(x[2])}</p></div>`).join("")}
async function reports(){let {data:s}=await sb.from("services").select("*");s=s||[];let total=s.reduce((a,x)=>a+Number(x.total||0),0);$("report").innerHTML=`<div class=grid><div class=list><b>${s.length}</b><br>Servis</div><div class=list><b>${s.filter(x=>x.type==="Bakım").length}</b><br>Bakım</div><div class=list><b>${s.filter(x=>x.type==="Arıza").length}</b><br>Arıza</div><div class=list><b>${total.toFixed(2)} ₺</b><br>Ciro</div></div>`}
async function logout(){await sb.auth.signOut();location.href="login.html"}
window.show=show;window.brandList=brandList;window.modelList=modelList;window.serviceType=serviceType;window.allChecks=allChecks;window.saveService=saveService;window.customers=customers;window.addCustomer=addCustomer;window.newFor=newFor;window.history=history;window.services=services;window.detail=detail;window.makePDF=makePDF;window.faults=faults;window.reports=reports;window.logout=logout;document.addEventListener("DOMContentLoaded",init);