const DBKEY="nitek_complete_v2";
let DB=load();
function load(){try{return JSON.parse(localStorage.getItem(DBKEY))||{customers:[],services:[],customBrands:{},faults:[],settings:{}}}catch(e){return{customers:[],services:[],customBrands:{},faults:[],settings:{}}}}
function save(){localStorage.setItem(DBKEY,JSON.stringify(DB))}
const $=id=>document.getElementById(id);
const esc=x=>String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function toast(t){let x=document.createElement("div");x.className="toast";x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2200)}
function show(id){
 document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));
 $(id)?.classList.add("active");
 document.querySelectorAll(".bottom button").forEach(x=>x.classList.remove("active"));
 document.querySelector(`[data-page="${id}"]`)?.classList.add("active");
 if(id==="home")home(); if(id==="customers")customers(); if(id==="services")services(); if(id==="faults")faults(); if(id==="reports")reports(); if(id==="service")newService();
}
function home(){
 const total=DB.services.reduce((a,s)=>a+Number(s.total||0),0);
 $("homeStats").innerHTML=`<div class="grid"><div class=list><b>${DB.customers.length}</b><br><span class=muted>Müşteri</span></div><div class=list><b>${DB.services.length}</b><br><span class=muted>Servis</span></div><div class=list><b>${DB.services.filter(s=>s.type==="Bakım").length}</b><br><span class=muted>Bakım</span></div><div class=list><b>${total.toFixed(2)} ₺</b><br><span class=muted>Ciro</span></div></div>`;
 $("recent").innerHTML=DB.services.slice(0,5).map(card).join("")||"<p class=muted>Henüz servis yok.</p>";
}
function card(s){return `<div class=list><span class=badge>${esc(s.type)}</span> <span class=badge>${esc(s.device)}</span><h3>${esc(s.customer)}</h3><p class=muted>${esc(s.brand)} ${esc(s.model)}<br>${esc(s.date)} ${esc(s.time)}</p><b>${Number(s.total||0).toFixed(2)} ₺</b><div class=actions><button class=light onclick="detail(${s.id})">Detayı Gör</button><button class=light onclick="makePDF(${s.id})">PDF</button></div></div>`}
function catalogs(d){return Object.assign({},NITEK_DATA.brands[d]||{},DB.customBrands[d]||{})}
function brandList(){let d=$("device").value,b=$("brand"),c=catalogs(d);b.innerHTML='<option value="">Marka seç</option>'+Object.keys(c).sort((a,z)=>a.localeCompare(z,"tr")).map(x=>`<option>${esc(x)}</option>`).join("");modelList()}
function modelList(){let c=catalogs($("device").value),b=$("brand").value,m=$("model");m.innerHTML='<option value="">Model seç</option>'+((c[b]||[]).map(x=>`<option>${esc(x)}</option>`).join(""))}
function serviceType(){let t=$("type").value;$("maintBox").classList.toggle("hidden",t!=="Bakım");$("faultBox").classList.toggle("hidden",t!=="Arıza");if(t==="Bakım")maintenance()}
function maintenance(){let a=NITEK_DATA.maintenance[$("device").value]||NITEK_DATA.maintenance.Diğer;$("checks").innerHTML=a.map((x,i)=>`<label class=check><input type=checkbox data-check="${i}"><span>${esc(x)}</span></label>`).join("")}
function checkAll(v){document.querySelectorAll("[data-check]").forEach(x=>x.checked=v)}
function newService(){
 let d=new Date(); if(!$("date").value)$("date").value=d.toISOString().slice(0,10); if(!$("time").value)$("time").value=d.toTimeString().slice(0,5);
 brandList(); serviceType();
}
function saveService(){
 let n=$("customer").value.trim(); if(!n){alert("Müşteri adı gerekli.");return}
 let type=$("type").value,device=$("device").value,a=NITEK_DATA.maintenance[device]||NITEK_DATA.maintenance.Diğer;
 let done=type==="Bakım"?a.filter((x,i)=>document.querySelector(`[data-check="${i}"]`)?.checked):[];
 let labor=Number($("labor").value)||0,parts=Number($("parts").value)||0;
 let s={id:Date.now(),customer:n,phone:$("phone").value,address:$("address").value,type,device,brand:$("brand").value,model:$("model").value,complaint:$("complaint").value,done,work:$("work").value,partsText:$("partsText").value,labor,parts,total:labor+parts,payment:$("payment").value,note:$("note").value,date:$("date").value,time:$("time").value};
 DB.services.unshift(s);let c=DB.customers.find(x=>x.name.toLocaleLowerCase("tr")===n.toLocaleLowerCase("tr"));if(!c)DB.customers.unshift({id:Date.now()+1,name:n,phone:s.phone,address:s.address,note:""});else{c.phone=s.phone;c.address=s.address}save();toast("Servis kaydedildi");show("services");
}
function services(){let q=($("serviceSearch").value||"").toLocaleLowerCase("tr");$("serviceList").innerHTML=DB.services.filter(s=>(s.customer+" "+s.brand+" "+s.model+" "+s.device).toLocaleLowerCase("tr").includes(q)).map(card).join("")||"<p class=muted>Servis kaydı yok.</p>"}
function customers(){let q=($("customerSearch").value||"").toLocaleLowerCase("tr");$("customerList").innerHTML=DB.customers.filter(c=>(c.name+" "+c.phone).toLocaleLowerCase("tr").includes(q)).map(c=>`<div class=list><h3>${esc(c.name)}</h3><p>📞 ${esc(c.phone)}<br>📍 ${esc(c.address)}</p><div class=actions><button class=blue onclick="newFor(${c.id})">Yeni Servis</button><button class=light onclick="history(${c.id})">Servis Geçmişi</button></div></div>`).join("")||"<p class=muted>Müşteri yok.</p>"}
function addCustomer(){let n=prompt("Ad soyad");if(!n)return;let p=prompt("Telefon")||"",a=prompt("Adres")||"",note=prompt("Müşteri notu")||"";DB.customers.unshift({id:Date.now(),name:n,phone:p,address:a,note});save();customers()}
function newFor(id){let c=DB.customers.find(x=>x.id===id);show("service");setTimeout(()=>{$("customer").value=c.name;$("phone").value=c.phone;$("address").value=c.address},50)}
function history(id){let c=DB.customers.find(x=>x.id===id),arr=DB.services.filter(s=>s.customer===c.name);$("historyTitle").innerHTML=`<h2>${esc(c.name)}</h2><p>${esc(c.phone)}<br>${esc(c.address)}</p>`;$("historyList").innerHTML=arr.map(card).join("")||"<p class=muted>Servis geçmişi yok.</p>";show("history")}
function detail(id){let s=DB.services.find(x=>x.id===id);$("detail").innerHTML=`<div class=card><button class=light onclick="show('services')">← Geri</button><h2>${esc(s.type)} • ${esc(s.device)}</h2><p><b>Müşteri:</b> ${esc(s.customer)}<br><b>Telefon:</b> ${esc(s.phone)}<br><b>Adres:</b> ${esc(s.address)}<br><b>Marka/Model:</b> ${esc(s.brand)} ${esc(s.model)}<br><b>Tarih:</b> ${esc(s.date)} ${esc(s.time)}</p><h3>📝 Şikâyet</h3><p>${esc(s.complaint)}</p><h3>☑️ Yapılan Kontroller</h3>${s.done?.length?`<ul>${s.done.map(x=>`<li>✓ ${esc(x)}</li>`).join("")}</ul>`:"<p class=muted>İşaretlenen kontrol yok.</p>"}<h3>🧰 Yapılan İşler</h3><p>${esc(s.work)}</p><h3>🔩 Parça / Malzeme</h3><p>${esc(s.partsText)}</p><p>İşçilik: ${s.labor.toFixed(2)} ₺<br>Parça: ${s.parts.toFixed(2)} ₺<br><b class=money>Toplam: ${s.total.toFixed(2)} ₺</b><br>Ödeme: ${esc(s.payment)}</p><h3>📝 Teknisyen Notu</h3><p>${esc(s.note)}</p><button class="primary full" onclick="makePDF(${s.id})">📄 PDF Oluştur</button></div>`;show("detail")}
function makePDF(id){let s=DB.services.find(x=>x.id===id),w=window.open("","_blank");if(!w){alert("PDF için açılır pencereye izin ver.");return}let logoHtml="";try{logoHtml=`<img src="logo.jpg" style="width:90px;height:90px;object-fit:contain">`}catch(e){}w.document.write(`<!doctype html><html lang=tr><head><meta charset=utf-8><title>NİTEK Servis Formu</title><style>body{font-family:Arial;padding:30px;color:#172033}header{display:flex;align-items:center;gap:18px;border-bottom:2px solid #07152f;padding-bottom:15px}h1{margin:0;font-size:22px}li{margin:7px 0}.btn{position:fixed;right:20px;top:20px;padding:12px 18px}@media print{.btn{display:none}}</style></head><body><button class=btn onclick="print()">🖨️ PDF / Yazdır</button><header>${logoHtml}<div><h1>NİTEK TEKNİK SERVİS</h1><div>Servis Formu</div></div></header><p><b>Müşteri:</b> ${esc(s.customer)}<br><b>Telefon:</b> ${esc(s.phone)}<br><b>Adres:</b> ${esc(s.address)}</p><p><b>Servis:</b> ${esc(s.type)}<br><b>Cihaz:</b> ${esc(s.device)}<br><b>Marka / Model:</b> ${esc(s.brand)} ${esc(s.model)}<br><b>Tarih / Saat:</b> ${esc(s.date)} ${esc(s.time)}</p><h3>Şikâyet</h3><p>${esc(s.complaint)}</p><h3>Yapılan Kontroller</h3><ul>${(s.done||[]).map(x=>`<li>✓ ${esc(x)}</li>`).join("")}</ul><h3>Yapılan İşler</h3><p>${esc(s.work)}</p><h3>Değişen Parça / Malzeme</h3><p>${esc(s.partsText)}</p><p><b>İşçilik:</b> ${s.labor.toFixed(2)} ₺<br><b>Parça:</b> ${s.parts.toFixed(2)} ₺<br><b>TOPLAM:</b> ${s.total.toFixed(2)} ₺<br><b>Ödeme:</b> ${esc(s.payment)}</p><h3>Not</h3><p>${esc(s.note)}</p><div style="margin-top:70px;display:flex;justify-content:space-between"><span>Müşteri İmzası: __________</span><span>Teknisyen İmzası: __________</span></div></body></html>`);w.document.close()}
function faults(){let q=($("faultSearch").value||"").toLocaleLowerCase("tr"),arr=[...NITEK_DATA.faults,...DB.faults];$("faultList").innerHTML=arr.filter(x=>x.join(" ").toLocaleLowerCase("tr").includes(q)).map(x=>`<div class=list><b>${esc(x[0])}</b> — ${esc(x[1])}<p class=muted>${esc(x[2])}</p></div>`).join("")}
function reports(){let total=DB.services.reduce((a,s)=>a+Number(s.total||0),0);$("report").innerHTML=`<div class=grid><div class=list><b>${DB.services.length}</b><br>Toplam servis</div><div class=list><b>${DB.customers.length}</b><br>Müşteri</div><div class=list><b>${total.toFixed(2)} ₺</b><br>Toplam ciro</div><div class=list><b>${DB.services.filter(s=>s.type==="Bakım").length}</b><br>Bakım</div></div>`}
function addBrand(){let d=$("newDevice").value,b=$("newBrand").value.trim(),m=$("newModel").value.trim();if(!b||!m)return alert("Marka ve model gir.");DB.customBrands[d]=DB.customBrands[d]||{};DB.customBrands[d][b]=DB.customBrands[d][b]||[];if(!DB.customBrands[d][b].includes(m))DB.customBrands[d][b].push(m);save();toast("Marka/model eklendi")}
function backup(){let blob=new Blob([JSON.stringify(DB,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="NITEK-yedek.json";a.click()}
function toggleTheme(){document.body.classList.toggle("dark");localStorage.setItem("nitek_theme",document.body.classList.contains("dark")?"dark":"light")}
function logout(){localStorage.removeItem("nitek_auth");location.href="login.html"}
window.show=show;window.brandList=brandList;window.modelList=modelList;window.serviceType=serviceType;window.checkAll=checkAll;window.saveService=saveService;window.addCustomer=addCustomer;window.newFor=newFor;window.history=history;window.detail=detail;window.makePDF=makePDF;window.faults=faults;window.addBrand=addBrand;window.backup=backup;window.toggleTheme=toggleTheme;window.logout=logout;window.services=services;window.customers=customers;
document.addEventListener("DOMContentLoaded",()=>{if(localStorage.getItem("nitek_auth")!=="1"){location.href="login.html";return} if(localStorage.getItem("nitek_theme")==="dark")document.body.classList.add("dark");home();show("home")});
